apiVersion: v2
name: cloudmetrics
description: Helm chart for the CloudMetrics application
type: application
version: 1.0.0
appVersion: "v1.0.0"
icon: https://raw.githubusercontent.com/cncf/artwork/refs/heads/main/other/cncf/icon/color/cncf-icon-color.svg
