apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudmetrics-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/prdktntwcklr/cloudmetrics'
    # TODO: Change to a specific release for production
    targetRevision: HEAD
    path: charts/cloudmetrics
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
