apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: 'https://prometheus-community.github.io/helm-charts'
      chart: kube-prometheus-stack
      targetRevision: '86.0.1'
      helm:
        valueFiles:
          - $root/deploy/observability/kube-prometheus-stack-values.yaml
    - repoURL: 'https://github.com/prdktntwcklr/cloudmetrics'
      # TODO: Change to a specific release for production
      targetRevision: refs/heads/main
      ref: root
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
