apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudmetrics-deployment
  labels:
    app: cloudmetrics
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudmetrics
  template:
    metadata:
      labels:
        app: cloudmetrics
    spec:
      containers:
        - name: cloudmetrics-app
          image: cloudmetrics:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
