apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudmetrics-monitoring
  labels:
    # This label must match your Prometheus installation's selector
    release: prometheus
spec:
  selector:
    matchLabels:
      app: cloudmetrics
  endpoints:
    - port: app-metrics
      interval: 15s
      path: /metrics
