apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  labels:
    app: {{ .Release.Name }}-api
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
    spec:
      containers:
        - name: api-service
          image: "{{ .Values.api.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.api.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: 8080

          # Ensures the container gets restarted if the process deadlocks
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10

          # Ensures zero-downtime deployments by waiting for HTTP server to be responsive
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5

          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
