apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-monitoring
  labels:
    # This label must match your Prometheus installation's selector
    release: {{ .Values.prometheusReleaseName | default "prometheus" }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  endpoints:
    - port: app-metrics
      interval: 15s
      path: /metrics
