repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana-community
    url: https://grafana-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  # 1. Prometheus, Grafana, and CRDs
  - name: prometheus
    namespace: monitoring
    chart: prometheus-community/kube-prometheus-stack
    version: "86.0.1"
    createNamespace: true
    values:
      - kube-prometheus-stack-values.yaml

  # 2. Loki for log aggregation
  - name: loki
    namespace: monitoring
    chart: grafana-community/loki
    version: "17.1.1"
    needs:
      - monitoring/prometheus
    values:
      - loki-values.yaml

  # 3. Alloy to gather and send logs
  - name: alloy
    namespace: monitoring
    chart: grafana/alloy
    version: "1.8.2"
    needs:
      - monitoring/loki
    values:
      - alloy-values.yaml
